name: path2json

on:
  push:
    branches: master

jobs:
  praise:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: process path to json
        run: |
          export TZ=Asia/Shanghai
          branch="master"
          type="defult"
          path="./img"
          file="public.json"
          time=$(date '+%s')
          url="https://cdn.jsdelivr.net/gh/${{ github.repository }}"
          if [[ type != "defult" ]];then url="${url}";else url="${url}@${branch}";fi
          raw_arr=$(find ${path} -type f ! -name '*.json' -exec ls -dl \{\} \; | awk '{print $9}')
          path_arr=$(for fp in ${raw_arr[@]};do if [[ ! -d ${fp} ]]; then printf "\"${fp#\.}\",";fi;done)
          content=$(printf "{\"src\":\"${url}\",\"src\":[${path_arr}]}")
          echo ${content/,\]/\]} > ${path}/${file}
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ secrets.EMAIL }}'
          git add ${path}/${file}
          git commit --date="${time}" --message="[general update] $(date -u --date=@"${time}" '+%Y-%m-%d')."
          git push https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
